export {default as ContactPage} from './contact'
export {default as TeamPage} from './team'
export {default as SponsorsPage} from './sponsors'
export {default as GalleryPage} from './gallery'
export {default as CrowdfundingPage} from './crowdfunding'
export {default as AchievementPage} from './achievements'
export {default as FormulaBharatPage} from './fbharat'
